name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Check formatting
      run: |-
        go fmt .
        git diff --exit-code

    - name: Run go vet
      run: go vet ./...

    - name: Build
      run: go build ./...

    - name: Run tests
      run: go test ./...